import manifest from '@/data/image-variants.json';

/** One rendition: the same crop at one width, in all three formats. */
export interface VariantFile {
  width: number;
  height: number;
  avif: string;
  webp: string;
  jpg: string;
}

/** The crop shapes `scripts/build-images.mjs` knows how to emit. */
export type VariantKind =
  | 'heroPortrait'
  | 'heroLandscape'
  | 'card'
  | 'studio'
  | 'thumb'
  | 'avatar';

export type VariantManifest = Record<string, Partial<Record<VariantKind, VariantFile[]>>>;

// Generated by `npm run build:images` and committed. Import it from SERVER
// components only — it is 8 entries of pure strings and has no business in a
// client bundle that is already fighting a 12 KB app-JS budget.
export const IMAGE_VARIANTS = manifest as unknown as VariantManifest;

export function variantsFor(
  src: string,
  kind: VariantKind,
  m: VariantManifest = IMAGE_VARIANTS,
): VariantFile[] {
  return m[src]?.[kind] ?? [];
}

export function srcSetFor(files: VariantFile[], format: 'avif' | 'webp' | 'jpg'): string {
  return files.map((f) => `${f[format]} ${f.width}w`).join(', ');
}

/** The six source sets a hand-written hero <picture> needs. */
export interface HeroPoster {
  portrait: { avif: string; webp: string; jpg: string; jpgSrc: string };
  landscape: { avif: string; webp: string; jpg: string };
}

/**
 * Null means "this poster has no pre-built crops" — an admin-uploaded photo
 * the build script has never seen. Callers must fall back to rendering the raw
 * `src`; a missing hero is far worse than an unoptimized one.
 */
export function heroPoster(src: string, m: VariantManifest = IMAGE_VARIANTS): HeroPoster | null {
  const portrait = variantsFor(src, 'heroPortrait', m);
  const landscape = variantsFor(src, 'heroLandscape', m);
  if (portrait.length === 0 || landscape.length === 0) return null;
  return {
    portrait: {
      avif: srcSetFor(portrait, 'avif'),
      webp: srcSetFor(portrait, 'webp'),
      jpg: srcSetFor(portrait, 'jpg'),
      jpgSrc: portrait[0].jpg,
    },
    landscape: {
      avif: srcSetFor(landscape, 'avif'),
      webp: srcSetFor(landscape, 'webp'),
      jpg: srcSetFor(landscape, 'jpg'),
    },
  };
}
